apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osservatorio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osservatorio.labels" . | nindent 4 }}
    {{- with .Values.deployment.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ include "osservatorio.replicaCount" . }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "osservatorio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "osservatorio.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osservatorio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.deployment.securityContext | nindent 10 }}
        image: {{ include "osservatorio.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.service.ports }}
        - name: {{ .name }}
          containerPort: {{ .targetPort }}
          protocol: {{ .protocol | default "TCP" }}
        {{- end }}
        env:
        {{- include "osservatorio.env" . | nindent 8 }}
        {{- $envValues := include "osservatorio.environmentValues" . | fromYaml }}
        {{- if $envValues.env }}
        {{- range $key, $value := $envValues.env }}
        - name: DATAFLOW_{{ $key | upper }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        resources:
          {{- include "osservatorio.resources" . | nindent 10 }}
        {{- if .Values.healthChecks.startup.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.healthChecks.startup.path }}
            port: {{ .Values.healthChecks.startup.port }}
          initialDelaySeconds: {{ .Values.healthChecks.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.startup.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.startup.failureThreshold }}
          successThreshold: {{ .Values.healthChecks.startup.successThreshold }}
        {{- end }}
        {{- if .Values.healthChecks.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthChecks.liveness.path }}
            port: {{ .Values.healthChecks.liveness.port }}
          initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.liveness.failureThreshold }}
          successThreshold: {{ .Values.healthChecks.liveness.successThreshold }}
        {{- end }}
        {{- if .Values.healthChecks.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthChecks.readiness.path }}
            port: {{ .Values.healthChecks.readiness.port }}
          initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.readiness.failureThreshold }}
          successThreshold: {{ .Values.healthChecks.readiness.successThreshold }}
        {{- end }}
        volumeMounts:
        {{- if .Values.storage.persistence.database.enabled }}
        - name: database-storage
          mountPath: /data/db
        {{- end }}
        {{- if .Values.storage.persistence.cache.enabled }}
        - name: cache-storage
          mountPath: /data/cache
        {{- end }}
        {{- if .Values.storage.persistence.backup.enabled }}
        - name: backup-storage
          mountPath: /data/backup
        {{- end }}
        {{- if .Values.configMap.create }}
        - name: config
          mountPath: /config
          readOnly: true
        {{- end }}
        {{- if .Values.secrets.create }}
        - name: secrets
          mountPath: /secrets
          readOnly: true
        {{- end }}
        - name: tmp
          mountPath: /tmp
      volumes:
      {{- if .Values.storage.persistence.database.enabled }}
      - name: database-storage
        persistentVolumeClaim:
          claimName: {{ include "osservatorio.fullname" . }}-db-pvc
      {{- end }}
      {{- if .Values.storage.persistence.cache.enabled }}
      - name: cache-storage
        persistentVolumeClaim:
          claimName: {{ include "osservatorio.fullname" . }}-cache-pvc
      {{- end }}
      {{- if .Values.storage.persistence.backup.enabled }}
      - name: backup-storage
        persistentVolumeClaim:
          claimName: {{ include "osservatorio.fullname" . }}-backup-pvc
      {{- end }}
      {{- if .Values.configMap.create }}
      - name: config
        configMap:
          name: {{ include "osservatorio.fullname" . }}-config
      {{- end }}
      {{- if .Values.secrets.create }}
      - name: secrets
        secret:
          secretName: {{ include "osservatorio.fullname" . }}-secrets
      {{- end }}
      - name: tmp
        emptyDir: {}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
