{{- if .Values.storage.persistence.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "osservatorio.fullname" . }}-db-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osservatorio.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    {{- toYaml .Values.storage.persistence.database.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.persistence.database.size }}
  {{- if .Values.storage.persistence.database.storageClass }}
  storageClassName: {{ .Values.storage.persistence.database.storageClass }}
  {{- end }}
{{- end }}
{{- if .Values.storage.persistence.cache.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "osservatorio.fullname" . }}-cache-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osservatorio.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  accessModes:
    {{- toYaml .Values.storage.persistence.cache.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.persistence.cache.size }}
  {{- if .Values.storage.persistence.cache.storageClass }}
  storageClassName: {{ .Values.storage.persistence.cache.storageClass }}
  {{- end }}
{{- end }}
{{- if .Values.storage.persistence.backup.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "osservatorio.fullname" . }}-backup-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osservatorio.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    {{- toYaml .Values.storage.persistence.backup.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.persistence.backup.size }}
  {{- if .Values.storage.persistence.backup.storageClass }}
  storageClassName: {{ .Values.storage.persistence.backup.storageClass }}
  {{- end }}
{{- end }}
