# Osservatorio ISTAT Data Platform - Docker Compose Configuration
# Development and testing environment

version: '3.8'

services:
  # Main FastAPI application
  osservatorio-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - osservatorio-data:/app/data
      - osservatorio-logs:/app/logs
    environment:
      - OSSERVATORIO_ENV=development
      - OSSERVATORIO_LOG_LEVEL=DEBUG
      - DATABASE_URL=sqlite:///data/databases/osservatorio_dev.db
      - DUCKDB_URL=data/databases/osservatorio_dev.duckdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    networks:
      - osservatorio-network
    restart: unless-stopped

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - osservatorio-network
    restart: unless-stopped

  # PostgreSQL for production-ready metadata storage (optional)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=osservatorio
      - POSTGRES_USER=osservatorio
      - POSTGRES_PASSWORD=osservatorio_dev_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    networks:
      - osservatorio-network
    restart: unless-stopped

  # Streamlit dashboard
  osservatorio-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - osservatorio-data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run dashboard/app.py
    depends_on:
      - osservatorio-api
    networks:
      - osservatorio-network
    restart: unless-stopped

  # Nginx reverse proxy (production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - osservatorio-api
      - osservatorio-dashboard
    networks:
      - osservatorio-network
    restart: unless-stopped

volumes:
  osservatorio-data:
    driver: local
  osservatorio-logs:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local

networks:
  osservatorio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
