apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: osservatorio-production

namespace: osservatorio-prod

resources:
- ../../manifests/namespaces.yaml
- ../../manifests/configmap.yaml
- ../../manifests/secret.yaml
- ../../manifests/storageclass.yaml
- ../../manifests/pv-pvc.yaml
- ../../manifests/rbac.yaml
- ../../manifests/deployment.yaml
- ../../manifests/service.yaml
- ../../manifests/service-headless.yaml
- ../../manifests/hpa.yaml
- ../../manifests/pdb.yaml
- networkpolicy.yaml

# Production-specific configurations
patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml
- hpa-patch.yaml

# Production-specific labels
commonLabels:
  environment: production
  tier: production

# High availability configuration
replicas:
- name: dataflow-analyzer
  count: 3

# Production images with specific versions
images:
- name: osservatorio/dataflow-analyzer
  newTag: v2.0.0
