apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: osservatorio-staging

namespace: osservatorio-staging

resources:
- ../../manifests/namespaces.yaml
- ../../manifests/configmap.yaml
- ../../manifests/secret.yaml
- ../../manifests/storageclass.yaml
- ../../manifests/pv-pvc.yaml
- ../../manifests/rbac.yaml
- ../../manifests/deployment.yaml
- ../../manifests/service.yaml
- ../../manifests/hpa.yaml

# Staging-specific configurations
patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

# Staging-specific labels
commonLabels:
  environment: staging
  tier: staging

# Resource configuration for staging
replicas:
- name: dataflow-analyzer
  count: 2

# Staging-specific images
images:
- name: osservatorio/dataflow-analyzer
  newTag: staging-latest
