#!/usr/bin/env python3
# Quick Pipeline Test - Auto-generated by setup
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.pipeline import PipelineService


async def quick_test():
    print("🚀 Quick Pipeline Test")
    service = PipelineService()
    await service.start_background_processing()

    status = await service.get_pipeline_status()
    print(f"Status: {status.get('status', 'unknown')}")
    print(f"Formats: {service.get_supported_formats()}")
    print("✅ Pipeline is ready for use!")


if __name__ == "__main__":
    asyncio.run(quick_test())
