# Daily backup CronJob for Osservatorio data
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataflow-analyzer-backup
  namespace: osservatorio
  labels:
    app.kubernetes.io/name: dataflow-analyzer
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: osservatorio-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  timeZone: "Europe/Rome"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 3600  # 1 hour timeout
      template:
        metadata:
          labels:
            app.kubernetes.io/name: dataflow-analyzer
            app.kubernetes.io/component: backup
            job-type: backup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: dataflow-analyzer
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
          - name: backup
            image: osservatorio/backup-utils:1.0.0
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Starting backup process at $(date)"

              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              BACKUP_DIR="/backup/osservatorio/${TIMESTAMP}"
              mkdir -p "$BACKUP_DIR"

              echo "Backing up SQLite database..."
              cp -r /data/db/* "$BACKUP_DIR/database/" 2>/dev/null || true

              echo "Backup completed successfully at $(date)"
            env:
            - name: DATAFLOW_VERSION
              value: "2.0.0"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: database-storage
              mountPath: /data/db
              readOnly: true
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
          volumes:
          - name: database-storage
            persistentVolumeClaim:
              claimName: dataflow-analyzer-db-pvc
          - name: backup-storage
            persistentVolumeClaim:
              claimName: dataflow-analyzer-backup-pvc
