apiVersion: v1
kind: ConfigMap
metadata:
  name: dataflow-analyzer-config
  namespace: osservatorio
  labels:
    app.kubernetes.io/name: dataflow-analyzer
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: osservatorio-platform
data:
  # Environment configuration
  DATAFLOW_ENVIRONMENT: "production"
  DATAFLOW_SERVICE_NAME: "dataflow-analyzer"
  DATAFLOW_SERVICE_VERSION: "2.0.0"
  DATAFLOW_NAMESPACE: "osservatorio"

  # Database configuration
  DATAFLOW_DATABASE_POOL_SIZE: "20"
  DATAFLOW_DATABASE_MAX_OVERFLOW: "40"
  DATAFLOW_DATABASE_POOL_TIMEOUT: "30"
  DATAFLOW_DATABASE_POOL_RECYCLE: "3600"

  # Redis configuration
  DATAFLOW_REDIS_HOST: "redis-cluster.osservatorio.svc.cluster.local"
  DATAFLOW_REDIS_PORT: "6379"
  DATAFLOW_REDIS_DB: "0"
  DATAFLOW_REDIS_MAX_CONNECTIONS: "100"
  DATAFLOW_REDIS_SOCKET_TIMEOUT: "5"
  DATAFLOW_REDIS_SOCKET_CONNECT_TIMEOUT: "5"
  DATAFLOW_REDIS_RETRY_ON_TIMEOUT: "true"

  # ISTAT API configuration
  DATAFLOW_ISTAT_API_BASE_URL: "https://esploradati.istat.it/SDMXWS/rest"
  DATAFLOW_ISTAT_API_TIMEOUT: "30"
  DATAFLOW_ISTAT_API_MAX_RETRIES: "3"
  DATAFLOW_ISTAT_API_BACKOFF_FACTOR: "0.3"
  DATAFLOW_ISTAT_API_RATE_LIMIT_CALLS: "100"
  DATAFLOW_ISTAT_API_RATE_LIMIT_PERIOD: "60"

  # Observability configuration
  DATAFLOW_OBSERVABILITY_OTEL_SERVICE_NAME: "dataflow-analyzer"
  DATAFLOW_OBSERVABILITY_OTEL_SERVICE_VERSION: "2.0.0"
  DATAFLOW_OBSERVABILITY_OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces"
  DATAFLOW_OBSERVABILITY_METRICS_PORT: "8001"
  DATAFLOW_OBSERVABILITY_METRICS_PATH: "/metrics"
  DATAFLOW_OBSERVABILITY_LOG_LEVEL: "INFO"
  DATAFLOW_OBSERVABILITY_LOG_FORMAT: "json"

  # Scaling configuration
  DATAFLOW_SCALING_WORKER_POOL_SIZE: "8"
  DATAFLOW_SCALING_MAX_CONCURRENT_REQUESTS: "200"
  DATAFLOW_SCALING_REQUEST_TIMEOUT: "300"
  DATAFLOW_SCALING_QUEUE_MAX_SIZE: "2000"
  DATAFLOW_SCALING_BATCH_SIZE: "20"
  DATAFLOW_SCALING_SCALE_UP_THRESHOLD: "0.8"
  DATAFLOW_SCALING_SCALE_DOWN_THRESHOLD: "0.2"

  # Health configuration
  DATAFLOW_HEALTH_STARTUP_TIMEOUT: "30"
  DATAFLOW_HEALTH_LIVENESS_TIMEOUT: "5"
  DATAFLOW_HEALTH_READINESS_TIMEOUT: "5"
  DATAFLOW_HEALTH_HEALTH_CHECK_INTERVAL: "10"
  DATAFLOW_HEALTH_UNHEALTHY_THRESHOLD: "3"
  DATAFLOW_HEALTH_HEALTHY_THRESHOLD: "2"

  # Feature flags
  DATAFLOW_ENABLE_DISTRIBUTED_CACHING: "true"
  DATAFLOW_ENABLE_TRACING: "true"
  DATAFLOW_ENABLE_METRICS: "true"
  DATAFLOW_ENABLE_CIRCUIT_BREAKER: "true"
