apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dataflow-analyzer-pdb
  namespace: osservatorio
  labels:
    app.kubernetes.io/name: dataflow-analyzer
    app.kubernetes.io/instance: dataflow-analyzer
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/component: availability
    app.kubernetes.io/part-of: osservatorio-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataflow-analyzer
      app.kubernetes.io/instance: dataflow-analyzer
