[theme]
primaryColor = "#0066CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "info"
